x-volumes:
  volumes:
    - &certs "${CERT_DIR}:/data/certs"

services:
  mariadb:
    platform: ${PLATFORM}
    image: mariadb:${MDB_TAG}
    container_name: mariadb
    volumes:
      - "./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./mariadb/init.sh:/docker-entrypoint-initdb.d/init.sh"
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    env_file:
      - ./WMAgent_unittest.secrets
    network_mode: "host"

  couchdb:
    platform: ${PLATFORM}
    image: registry.cern.ch/cmsweb/wmagent-couchdb:${COUCH_TAG}
    container_name: couchdb
    volumes:
      - *certs
      - "./WMAgent_unittest.secrets:/data/admin/wmagent/WMAgent.secrets"
    ports:
      - 5984:5984
    network_mode: "host"

  wmcore-dev:
    platform: ${PLATFORM}
    image: registry.cern.ch/cmsweb/wmcore-dev:latest
    container_name: wmcore-dev
    volumes:
      - *certs
      - ${WMCORE_CODE_DIR}:/workspaces/WMCore:cached
      - "./WMAgent_unittest.secrets:/data/admin/wmagent/WMAgent.secrets"
    environment:
      - X509_USER_CERT=/data/certs/usercert.pem
      - X509_USER_KEY=/data/certs/userkey_nopwd.pem
      - X509_HOST_CERT=/data/certs/usercert.pem
      - X509_HOST_KEY=/data/certs/userkey_nopwd.pem
      - DEVCONTAINER_DIR=/workspaces/WMCore/${DEVCONTAINER_DIRNAME}
    env_file:
      - ./WMAgent_unittest.secrets
    depends_on:
      - mariadb
      - couchdb
    network_mode: "host"
